---
  - name: Docker pull {{ broker_image }}
    docker_image:
      name: "{{ broker_image }}"

  - name: Docker pull {{ etcd_image }}
    docker_image:
      name: "{{ etcd_image }}"

  - name: Copying services.yaml
    copy:
      src: services.yaml
      dest: /tmp/services.yaml

  - name: Copying route.yaml
    copy:
      src: route.yaml
      dest: /tmp/route.yaml

  - name: Creating etcd-deployment.yaml
    template:
      src: etcd-deployment.yaml.j2
      dest: /tmp/etcd-deployment.yaml

  - name: Creating broker-deployment.yaml
    template:
      src: broker-deployment.yaml.j2
      dest: /tmp/broker-deployment.yaml

  - name: Create ansible-service-broker namespace and services
    shell: "{{ oc_cmd }} create -f /tmp/services.yaml"

  - name: Create ansible-service-broker route
    shell: "{{ oc_cmd }} create -f /tmp/route.yaml"

  - name: Get route for ansible-service-broker
    shell: "'{{ oc_cmd }}' get routes -n ansible-service-broker| grep ansible-service-broker | awk '{print $2}'"
    retries: 6
    delay: 10

  - name: Create etcd deployment
    shell: "{{ oc_cmd }} create -f /tmp/etcd-deployment.yaml"

  - name: Create ansible-service-broker deployment
    shell: "{{ oc_cmd }} create -f /tmp/broker-deployment.yaml"

  - name: Waiting 10 minutes for ASB etcd pod
    action:
      shell "{{ oc_cmd }}" get pods -n ansible-service-broker | grep -iEm1 "etcd.*?running" | grep -v deploy
    until: wait_for_asb_etcd_pod.rc == 0
    retries: 60
    delay: 10

  - name: Waiting 10 minutes for ASB pod
    action:
      shell "{{ oc_cmd }}" get pods -n ansible-service-broker | grep -iEm1 "asb.*?running" | grep -v deploy
    until: wait_for_asb_pod.rc == 0
    retries: 60
    delay: 10

  - set_fact:
      ansible_service_broker_route:  "{{ result_get_route_asb.stdout }}"

  - name: Bootstrap Ansible Service Broker
    shell: curl -X POST {{ ansible_service_broker_route }}/v2/bootstrap

  - name: Creating /tmp/ansible_service_broker.yaml
    template:
      src: ansible_service_broker.yaml.j2
      dest: /tmp/ansible_service_broker.yaml
      owner: root
      group: root
      mode: 0644

  - name: Create Broker resource in Service Catalog
    shell: "{{ kubectl_cmd }} --kubeconfig=/root/.kube/service-catalog.config create -f /tmp/ansible_service_broker.yaml"
