#
# We are looking up the ec2 facts and storing them in a host variable
# so a later play can retrieve the data.
#
- hosts: localhost
  gather_facts: True
  tasks:
    - name: EC2 Remote Facts
      ec2_remote_facts:
        filters:
          instance-state-name: running
          "tag:Name": "{{ instance_name }}"
        region: "{{ aws_region }}"
      register: my_ec2_facts

- hosts: tag_Name_{{ instance_lookup_value }}
  gather_facts: True
  become: True
  pre_tasks:
    - name: Setting fact of security group id
      set_fact:
        my_security_group_id: "{{ hostvars.localhost.my_ec2_facts.instances[0].groups[0].id }}"
  vars_prompt:
    - name: dockerhub_user_name
      prompt: "Enter your dockerhub username: "
      private: no
    - name: dockerhub_user_password
      prompt: "Enter your dockerhub password: "
      private: yes
    - name: dockerhub_org
      prompt: "Enter the dockerhub organization you'd like to pull images from: "
      private: no
  roles:
    - ebs_volumes
    - aws_repo_setup
    - packages
    - docker_setup
    - { role: ssl_setup, when: use_ssl == True }
    - openshift_setup
    - env_hacks
    - { role: ansible_service_broker_setup, when: deploy_asb == True}
    - { role: helios_broker_setup, when: deploy_helios == True}
    - create_broker_secrets
  post_tasks:
    - set_fact:
        msg: |
            EC-2 Instance Tags:        Name={{ instance_name }}
            Hostname:                  {{ hostname }}
            SSH Key Name:              {{ ssh_key_name }}
            Region:                    {{ aws_region }}
            Web: https://{{ hostname }}:8443
            CLI: oc login --insecure-skip-tls-verify {{ hostname }}:8443 -u {{ cluster_user }} -p {{ cluster_user_password }}
    - debug:
        msg: "{{ msg.split('\n') }}"
